name: CI/CD Irrigação Inteligente

on:
  workflow_dispatch:
    inputs:
      run_train:
        description: "Rodar treino de ML?"
        type: choice
        options: [ "yes", "no" ]
        default: "yes"
      run_build:
        description: "Rodar build do firmware?"
        type: choice
        options: [ "yes", "no" ]
        default: "yes"
      deploy_ota:
        description: "Fazer OTA no ESP32?"
        type: choice
        options: [ "yes", "no" ]
        default: "no"

jobs:

  train-ml:
    if: ${{ github.event.inputs.run_train == 'yes' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r coleta_dados/requirements.txt

      - name: Run training
        run: python coleta_dados/treinar_modelo.py

      - name: Upload ML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            coleta_dados/ia_params.h
            coleta_dados/*.pkl
            coleta_dados/*.csv

  build-firmware:
    if: ${{ github.event.inputs.run_build == 'yes' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Baixa artefatos de ML apenas se o treino foi executado
      - name: Download ML artifacts
        if: ${{ github.event.inputs.run_train == 'yes' }}
        uses: actions/download-artifact@v4
        with:
          name: ml-artifacts
          path: esp32_firmware/components/ml

      - name: Build firmware
        run: |
          GIT_BRANCH="${GITHUB_REF_NAME}"
          GIT_SHA_SHORT="$(echo "${GITHUB_SHA}" | cut -c1-7)"
          BUILD_DATE="$(date -u +%Y%m%d)"
          FW_VERSION="${GIT_BRANCH}-${GIT_SHA_SHORT}-${BUILD_DATE}-run${GITHUB_RUN_NUMBER}"
          echo "Firmware version: ${FW_VERSION}"
          cd esp32_firmware
          idf.py -DPROJECT_VER="${FW_VERSION}" build

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: esp32_firmware/build/ia_automated_irrigation_system.bin

  ota-deploy:
    if: ${{ github.event.inputs.deploy_ota == 'yes' }}
    runs-on: [self-hosted, Linux, X64]
    needs: [build-firmware]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download firmware
        uses: actions/download-artifact@v4
        with:
          name: firmware-bin
          path: .

      - name: Deploy OTA to ESP32
        run: |
          curl -v --http1.1 \
            -H "Connection: close" \
            -H "Content-Type: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.OTA_TOKEN }}" \
            --data-binary @ia_automated_irrigation_system.bin \
            http://${{ secrets.ESP32_IP }}:${{ secrets.OTA_PORT }}/ota
